### ISSUE TITLE
请教问题

### ISSUE THREAD

**Issue by lightStarrr** [YoungLee-coder/Mooc-CDCAS#2]
您好，我也在编写这个网课平台的自动刷课，尝试过更换自动识别验证码为您推荐的，但依旧封号，所以想请教一下怎么办。我在您的博客里面找了一下没找到您的邮箱，介意提供一下您的联系方式吗？

**Comment by lightStarrr** [comment]
我的联系方式
QQ：2733977932
微信：z2733977932
邮箱：mango@little-mango.cn

**Comment by YoungLee-coder** [comment]
已添加
